linkedin:
  job_card: ".base-card"
  job_title: ".base-search-card__title"
  job_url: "a"
  job_description: ".description__text"

indeed:
  job_card: ".job_seen_beacon"
  job_title: "h2.jobTitle"
  job_url: "a[data-jk]"
  job_description: "#jobDescriptionText"

wttj:
  job_card: "article"
  job_title: "h4"
  job_url: "a"
  job_description: ".sc-10p0y79-0"

apec:
  job_card: ".container-resultat"
  job_title: ".card-title"
  job_url: "a"
  job_description: ".details-offre-description"
